#include <Graphics/Parameters.h>

namespace graphics {

namespace {
// These are API-neutral numeric values matching the historical GL enum wire
// values used across existing state encoding/comparisons.
constexpr u32 WIRE_RGB_VALUE = 0x1907U;
constexpr u32 WIRE_RGBA_VALUE = 0x1908U;
constexpr u32 WIRE_RG_VALUE = 0x8227U;
constexpr u32 WIRE_RED_VALUE = 0x1903U;
constexpr u32 WIRE_DEPTH_COMPONENT_VALUE = 0x1902U;
constexpr u32 WIRE_LUMINANCE_VALUE = 0x1909U;
constexpr u32 WIRE_RGB8_VALUE = 0x8051U;
constexpr u32 WIRE_RGBA8_VALUE = 0x8058U;
constexpr u32 WIRE_RGBA4_VALUE = 0x8056U;
constexpr u32 WIRE_RGB5_A1_VALUE = 0x8057U;
constexpr u32 WIRE_RG8_VALUE = 0x822BU;
constexpr u32 WIRE_R16F_VALUE = 0x822DU;
constexpr u32 WIRE_DEPTH_COMPONENT24_VALUE = 0x81A6U;
constexpr u32 WIRE_RG32F_VALUE = 0x8230U;
constexpr u32 WIRE_COLOR_INDEX8_VALUE = 0x80E5U;

constexpr u32 WIRE_UNSIGNED_BYTE_VALUE = 0x1401U;
constexpr u32 WIRE_UNSIGNED_SHORT_VALUE = 0x1403U;
constexpr u32 WIRE_UNSIGNED_INT_VALUE = 0x1405U;
constexpr u32 WIRE_FLOAT_VALUE = 0x1406U;
constexpr u32 WIRE_UNSIGNED_SHORT_5_6_5_VALUE = 0x8363U;
constexpr u32 WIRE_UNSIGNED_SHORT_5_5_5_1_VALUE = 0x8034U;
constexpr u32 WIRE_UNSIGNED_SHORT_4_4_4_4_VALUE = 0x8033U;

constexpr u32 WIRE_TEXTURE_2D_VALUE = 0x0DE1U;
constexpr u32 WIRE_TEXTURE_2D_MULTISAMPLE_VALUE = 0x9100U;
constexpr u32 WIRE_RENDERBUFFER_VALUE = 0x8D41U;
constexpr u32 WIRE_TEXTURE_EXTERNAL_OES_VALUE = 0x8D65U;

constexpr u32 WIRE_FRAMEBUFFER_VALUE = 0x8D40U;
constexpr u32 WIRE_DRAW_FRAMEBUFFER_VALUE = 0x8CA9U;
constexpr u32 WIRE_READ_FRAMEBUFFER_VALUE = 0x8CA8U;

constexpr u32 WIRE_COLOR_ATTACHMENT0_VALUE = 0x8CE0U;
constexpr u32 WIRE_COLOR_ATTACHMENT1_VALUE = 0x8CE1U;
constexpr u32 WIRE_COLOR_ATTACHMENT2_VALUE = 0x8CE2U;
constexpr u32 WIRE_COLOR_ATTACHMENT3_VALUE = 0x8CE3U;
constexpr u32 WIRE_COLOR_ATTACHMENT4_VALUE = 0x8CE4U;
constexpr u32 WIRE_DEPTH_ATTACHMENT_VALUE = 0x8D00U;

constexpr u32 WIRE_BLEND_VALUE = 0x0BE2U;
constexpr u32 WIRE_CULL_FACE_VALUE = 0x0B44U;
constexpr u32 WIRE_DEPTH_TEST_VALUE = 0x0B71U;
constexpr u32 WIRE_DEPTH_CLAMP_VALUE = 0x864FU;
constexpr u32 WIRE_CLIP_DISTANCE0_VALUE = 0x3000U;
constexpr u32 WIRE_DITHER_VALUE = 0x0BD0U;
constexpr u32 WIRE_POLYGON_OFFSET_FILL_VALUE = 0x8037U;
constexpr u32 WIRE_SCISSOR_TEST_VALUE = 0x0C11U;

constexpr u32 WIRE_READ_ONLY_VALUE = 0x88B8U;
constexpr u32 WIRE_WRITE_ONLY_VALUE = 0x88B9U;
constexpr u32 WIRE_READ_WRITE_VALUE = 0x88BAU;

constexpr u32 WIRE_NEAREST_VALUE = 0x2600U;
constexpr u32 WIRE_LINEAR_VALUE = 0x2601U;
constexpr u32 WIRE_NEAREST_MIPMAP_NEAREST_VALUE = 0x2700U;
constexpr u32 WIRE_LINEAR_MIPMAP_NEAREST_VALUE = 0x2701U;
constexpr u32 WIRE_CLAMP_TO_EDGE_VALUE = 0x812FU;
constexpr u32 WIRE_REPEAT_VALUE = 0x2901U;
constexpr u32 WIRE_MIRRORED_REPEAT_VALUE = 0x8370U;

constexpr u32 WIRE_FRONT_VALUE = 0x0404U;
constexpr u32 WIRE_BACK_VALUE = 0x0405U;
constexpr u32 WIRE_FRONT_AND_BACK_VALUE = 0x0408U;

constexpr u32 WIRE_LEQUAL_VALUE = 0x0203U;
constexpr u32 WIRE_LESS_VALUE = 0x0201U;
constexpr u32 WIRE_ALWAYS_VALUE = 0x0207U;

constexpr u32 WIRE_ZERO_VALUE = 0U;
constexpr u32 WIRE_ONE_VALUE = 1U;
constexpr u32 WIRE_SRC_ALPHA_VALUE = 0x0302U;
constexpr u32 WIRE_DST_ALPHA_VALUE = 0x0304U;
constexpr u32 WIRE_ONE_MINUS_SRC_ALPHA_VALUE = 0x0303U;
constexpr u32 WIRE_CONSTANT_ALPHA_VALUE = 0x8003U;
constexpr u32 WIRE_ONE_MINUS_CONSTANT_ALPHA_VALUE = 0x8004U;
constexpr u32 WIRE_SRC1_COLOR_VALUE = 0x88F9U;
constexpr u32 WIRE_ONE_MINUS_SRC1_COLOR_VALUE = 0x88FAU;
constexpr u32 WIRE_SRC1_ALPHA_VALUE = 0x8589U;
constexpr u32 WIRE_ONE_MINUS_SRC1_ALPHA_VALUE = 0x88FBU;

constexpr u32 WIRE_TRIANGLES_VALUE = 0x0004U;
constexpr u32 WIRE_TRIANGLE_STRIP_VALUE = 0x0005U;
constexpr u32 WIRE_TRIANGLE_FAN_VALUE = 0x0006U;
constexpr u32 WIRE_LINES_VALUE = 0x0001U;

constexpr u32 WIRE_COLOR_BUFFER_BIT_VALUE = 0x00004000U;
constexpr u32 WIRE_DEPTH_BUFFER_BIT_VALUE = 0x00000100U;
constexpr u32 WIRE_STENCIL_BUFFER_BIT_VALUE = 0x00000400U;
} // namespace

namespace colorFormat {
	ColorFormatParam RED_GREEN_BLUE(WIRE_RGB_VALUE); // Windows has a macro called RGB
	ColorFormatParam RGBA(WIRE_RGBA_VALUE);
	ColorFormatParam RG(WIRE_RG_VALUE);
	ColorFormatParam RED(WIRE_RED_VALUE);
	ColorFormatParam DEPTH(WIRE_DEPTH_COMPONENT_VALUE);
	ColorFormatParam LUMINANCE(WIRE_LUMINANCE_VALUE);
}

namespace internalcolorFormat {
	InternalColorFormatParam NOCOLOR(0U);
	InternalColorFormatParam RGB8(WIRE_RGB8_VALUE);
	InternalColorFormatParam RGBA8(WIRE_RGBA8_VALUE);
	InternalColorFormatParam RGBA4(WIRE_RGBA4_VALUE);
	InternalColorFormatParam RGB5_A1(WIRE_RGB5_A1_VALUE);
	InternalColorFormatParam RG(WIRE_RG8_VALUE);
	InternalColorFormatParam R16F(WIRE_R16F_VALUE);
	InternalColorFormatParam DEPTH(WIRE_DEPTH_COMPONENT24_VALUE);
	InternalColorFormatParam RG32F(WIRE_RG32F_VALUE);
	InternalColorFormatParam LUMINANCE(WIRE_LUMINANCE_VALUE);
	InternalColorFormatParam COLOR_INDEX8(WIRE_COLOR_INDEX8_VALUE);
}

namespace datatype {
	DatatypeParam UNSIGNED_BYTE(WIRE_UNSIGNED_BYTE_VALUE);
	DatatypeParam UNSIGNED_SHORT(WIRE_UNSIGNED_SHORT_VALUE);
	DatatypeParam UNSIGNED_INT(WIRE_UNSIGNED_INT_VALUE);
	DatatypeParam FLOAT(WIRE_FLOAT_VALUE);
	DatatypeParam UNSIGNED_SHORT_5_6_5(WIRE_UNSIGNED_SHORT_5_6_5_VALUE);
	DatatypeParam UNSIGNED_SHORT_5_5_5_1(WIRE_UNSIGNED_SHORT_5_5_5_1_VALUE);
	DatatypeParam UNSIGNED_SHORT_4_4_4_4(WIRE_UNSIGNED_SHORT_4_4_4_4_VALUE);
}

namespace textureTarget {
	TextureTargetParam TEXTURE_2D(WIRE_TEXTURE_2D_VALUE);
	TextureTargetParam TEXTURE_2D_MULTISAMPLE(WIRE_TEXTURE_2D_MULTISAMPLE_VALUE);
	TextureTargetParam RENDERBUFFER(WIRE_RENDERBUFFER_VALUE);
	TextureTargetParam TEXTURE_EXTERNAL(WIRE_TEXTURE_EXTERNAL_OES_VALUE);
}

namespace bufferTarget {
	BufferTargetParam FRAMEBUFFER(WIRE_FRAMEBUFFER_VALUE);
	BufferTargetParam DRAW_FRAMEBUFFER(WIRE_DRAW_FRAMEBUFFER_VALUE);
	BufferTargetParam READ_FRAMEBUFFER(WIRE_READ_FRAMEBUFFER_VALUE);
}

namespace bufferAttachment {
	BufferAttachmentParam COLOR_ATTACHMENT0(WIRE_COLOR_ATTACHMENT0_VALUE);
	BufferAttachmentParam COLOR_ATTACHMENT1(WIRE_COLOR_ATTACHMENT1_VALUE);
	BufferAttachmentParam COLOR_ATTACHMENT2(WIRE_COLOR_ATTACHMENT2_VALUE);
	BufferAttachmentParam COLOR_ATTACHMENT3(WIRE_COLOR_ATTACHMENT3_VALUE);
	BufferAttachmentParam COLOR_ATTACHMENT4(WIRE_COLOR_ATTACHMENT4_VALUE);
	BufferAttachmentParam DEPTH_ATTACHMENT(WIRE_DEPTH_ATTACHMENT_VALUE);
}

namespace enable {
	EnableParam BLEND(WIRE_BLEND_VALUE);
	EnableParam CULL_FACE(WIRE_CULL_FACE_VALUE);
	EnableParam DEPTH_TEST(WIRE_DEPTH_TEST_VALUE);
	EnableParam DEPTH_CLAMP(WIRE_DEPTH_CLAMP_VALUE);
	EnableParam CLIP_DISTANCE0(WIRE_CLIP_DISTANCE0_VALUE);
	EnableParam DITHER(WIRE_DITHER_VALUE);
	EnableParam POLYGON_OFFSET_FILL(WIRE_POLYGON_OFFSET_FILL_VALUE);
	EnableParam SCISSOR_TEST(WIRE_SCISSOR_TEST_VALUE);
}

namespace textureIndices {
	TextureUnitParam Tex[2] = { 0U, 1U };
	TextureUnitParam DepthTex(2U);
	TextureUnitParam ZLUTTex(3U);
	TextureUnitParam PaletteTex(4U);
	TextureUnitParam MSTex[2] = { 5U, 6U };
}

namespace textureImageUnits {
	ImageUnitParam DepthZ(2U);
	ImageUnitParam DepthDeltaZ(3U);
	ImageUnitParam DepthZCopy(4U);
	ImageUnitParam DepthDeltaZCopy(5U);
}

namespace textureImageAccessMode {
	ImageAccessModeParam READ_ONLY(WIRE_READ_ONLY_VALUE);
	ImageAccessModeParam WRITE_ONLY(WIRE_WRITE_ONLY_VALUE);
	ImageAccessModeParam READ_WRITE(WIRE_READ_WRITE_VALUE);
}

namespace textureParameters {
	TextureParam FILTER_NEAREST(WIRE_NEAREST_VALUE);
	TextureParam FILTER_LINEAR(WIRE_LINEAR_VALUE);
	TextureParam FILTER_NEAREST_MIPMAP_NEAREST(WIRE_NEAREST_MIPMAP_NEAREST_VALUE);
	TextureParam FILTER_LINEAR_MIPMAP_NEAREST(WIRE_LINEAR_MIPMAP_NEAREST_VALUE);
	TextureParam WRAP_CLAMP_TO_EDGE(WIRE_CLAMP_TO_EDGE_VALUE);
	TextureParam WRAP_REPEAT(WIRE_REPEAT_VALUE);
	TextureParam WRAP_MIRRORED_REPEAT(WIRE_MIRRORED_REPEAT_VALUE);
}

namespace cullMode {
	CullModeParam FRONT(WIRE_BACK_VALUE);
	CullModeParam BACK(WIRE_FRONT_VALUE);
	CullModeParam FRONT_AND_BACK(WIRE_FRONT_AND_BACK_VALUE);
}

namespace compare {
	CompareParam LEQUAL(WIRE_LEQUAL_VALUE);
	CompareParam LESS(WIRE_LESS_VALUE);
	CompareParam ALWAYS(WIRE_ALWAYS_VALUE);
}

namespace blend {
	BlendParam ZERO(WIRE_ZERO_VALUE);
	BlendParam ONE(WIRE_ONE_VALUE);
	BlendParam SRC_ALPHA(WIRE_SRC_ALPHA_VALUE);
	BlendParam DST_ALPHA(WIRE_DST_ALPHA_VALUE);
	BlendParam ONE_MINUS_SRC_ALPHA(WIRE_ONE_MINUS_SRC_ALPHA_VALUE);
	BlendParam CONSTANT_ALPHA(WIRE_CONSTANT_ALPHA_VALUE);
	BlendParam ONE_MINUS_CONSTANT_ALPHA(WIRE_ONE_MINUS_CONSTANT_ALPHA_VALUE);
	BlendParam SRC1_COLOR(WIRE_SRC1_COLOR_VALUE);
	BlendParam ONE_MINUS_SRC1_COLOR(WIRE_ONE_MINUS_SRC1_COLOR_VALUE);
	BlendParam SRC1_ALPHA(WIRE_SRC1_ALPHA_VALUE);
	BlendParam ONE_MINUS_SRC1_ALPHA(WIRE_ONE_MINUS_SRC1_ALPHA_VALUE);
}

namespace drawmode {
	DrawModeParam TRIANGLES(WIRE_TRIANGLES_VALUE);
	DrawModeParam TRIANGLE_STRIP(WIRE_TRIANGLE_STRIP_VALUE);
	DrawModeParam TRIANGLE_FAN(WIRE_TRIANGLE_FAN_VALUE);
	DrawModeParam LINES(WIRE_LINES_VALUE);
}

namespace blitMask {
	BlitMaskParam COLOR_BUFFER(WIRE_COLOR_BUFFER_BIT_VALUE);
	BlitMaskParam DEPTH_BUFFER(WIRE_DEPTH_BUFFER_BIT_VALUE);
	BlitMaskParam STENCIL_BUFFER(WIRE_STENCIL_BUFFER_BIT_VALUE);
}

} // namespace graphics
