#!/usr/bin/env bash
# shellcheck shell=bash

rvk2_pm_append_candidate_deep_telemetry_env() {
  local out_array_name="$1"
  local -n _deep_out="${out_array_name}"

  _deep_out+=(
    "REALITYVK_SMOKE_LAUNCH_LOG=${CANDIDATE_LAUNCH_LOG_OUT}"
    "REALITYVK_SMOKE_REQUIRE_READBACK_MARKER=1"
    "REALITYVK_SMOKE_READBACK_MARKER_REGEX=VK readback debug: kind=(pixel|color)"
    "REALITYVK2_TRACE_FILE=${CANDIDATE_TRACE_OUT}"
    "REALITYVK2_CAPTURE_RDP_TRACE=1"
    "REALITYVK2_PACKET_TRACE_FILE=${CANDIDATE_PACKET_TRACE_OUT}"
    "REALITYVK2_FRAME_FORENSICS_FILE=${CANDIDATE_FRAME_FORENSICS_OUT}"
    "REALITYVK_VK_TRACE_FBO=1"
    "REALITYVK_VK_TRACE_FBO_LIMIT=${DEEP_TELEMETRY_FBO_TRACE_LIMIT}"
    "REALITYVK_VK_DEBUG_READBACK=1"
    "REALITYVK_VK_DEBUG_READBACK_LIMIT=${DEEP_TELEMETRY_READBACK_LIMIT}"
    "REALITYVK_RVK2_DEBUG_TMEM32_COMPARE=1"
  )
  if [[ "${DEEP_TELEMETRY_TRACE_LOG_SUMMARY}" == "1" ]]; then
    _deep_out+=("REALITYVK2_TRACE_LOG_SUMMARY=1")
  fi
  if [[ "${DEEP_TELEMETRY_HISTORY_MERGE_LOG}" == "1" ]]; then
    _deep_out+=("REALITYVK_RVK2_DEBUG_HISTORY_MERGE_LOG=${CANDIDATE_HISTORY_MERGE_LOG_OUT}")
  fi
  if [[ "${DEEP_TELEMETRY_OVERWRITE_LOG}" == "1" ]]; then
    _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG=${CANDIDATE_OVERWRITE_LOG_OUT}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_LIMIT=${DEEP_TELEMETRY_OVERWRITE_LOG_LIMIT}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_INCLUDE_BLACK_WRITES=${DEEP_TELEMETRY_OVERWRITE_LOG_INCLUDE_BLACK_WRITES}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_INCLUDE_ALL_WRITES=${DEEP_TELEMETRY_OVERWRITE_LOG_INCLUDE_ALL_WRITES}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_INCLUDE_TEXEL_DETAIL=${DEEP_TELEMETRY_OVERWRITE_LOG_INCLUDE_TEXEL_DETAIL}")
    if [[ -n "${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_IDS_EFFECTIVE}" ]]; then
      _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_PACKET_IDS=${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_IDS_EFFECTIVE}")
    fi
    if [[ -n "${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_MIN}" ]]; then
      _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_PACKET_MIN=${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_MIN}")
    fi
    if [[ -n "${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_MAX}" ]]; then
      _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_PACKET_MAX=${DEEP_TELEMETRY_OVERWRITE_LOG_PACKET_MAX}")
    fi
    if [[ -n "${DEEP_TELEMETRY_OVERWRITE_LOG_WORK_MIN}" ]]; then
      _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_WORK_MIN=${DEEP_TELEMETRY_OVERWRITE_LOG_WORK_MIN}")
    fi
    if [[ -n "${DEEP_TELEMETRY_OVERWRITE_LOG_WORK_MAX}" ]]; then
      _deep_out+=("REALITYVK_RVK2_DEBUG_OVERWRITE_LOG_WORK_MAX=${DEEP_TELEMETRY_OVERWRITE_LOG_WORK_MAX}")
    fi
  fi
  if [[ "${DEEP_TELEMETRY_TRIANGLE_PACKET_LOG}" == "1" ]]; then
    _deep_out+=("REALITYVK_RVK2_DEBUG_TRIANGLE_PACKET_LOG=${CANDIDATE_TRIANGLE_PACKET_LOG_OUT}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_TRIANGLE_PACKET_LOG_LIMIT=${DEEP_TELEMETRY_TRIANGLE_PACKET_LOG_LIMIT}")
  fi
  if [[ "${DEEP_TELEMETRY_EXECUTOR_PRESENT_DUMP}" == "1" ]]; then
    _deep_out+=("REALITYVK_RVK2_DEBUG_EXECUTOR_PRESENT_DUMP=${CANDIDATE_EXECUTOR_PRESENT_DUMP_OUT}")
    _deep_out+=("REALITYVK_RVK2_DEBUG_EXECUTOR_PRESENT_DUMP_FRAME=${DEEP_TELEMETRY_EXECUTOR_PRESENT_DUMP_FRAME}")
  fi
}

rvk2_pm_append_candidate_debug_env() {
  local out_array_name="$1"
  local -n _debug_out="${out_array_name}"

  _debug_out+=(
    "REALITYVK_RVK2_DEBUG_ENABLE_SURFACE_HISTORY_BOOTSTRAP=${RVK2_ENABLE_SURFACE_HISTORY_BOOTSTRAP}"
    "REALITYVK_RVK2_DEBUG_ENABLE_CROSS_SURFACE_BOOTSTRAP=${RVK2_ENABLE_CROSS_SURFACE_BOOTSTRAP}"
    "REALITYVK_RVK2_DEBUG_DISABLE_VI_HISTORY_PRESENT=${RVK2_DISABLE_VI_HISTORY_PRESENT}"
    "REALITYVK_RVK2_DEBUG_PREFER_LIVE_SURFACE_OVER_HISTORY=${RVK2_PREFER_LIVE_SURFACE_OVER_HISTORY}"
  )
}
